version: "3.8"

services:
  animeav1-mal-sync:
    image: ovelayos/animeav1-mal-sync:1.7.3
    container_name: animeav1-mal-sync
    restart: unless-stopped

    ports:
      - "8787:8787"

    environment:
      SYNC_INTERVAL_MINUTES: "60"
      DRY_RUN: "true"
      ONLY_INCREASE: "true"
      AUTO_SYNC: "false"

      TITLE_MATCH_THRESHOLD: "80"
      REVERSE_TITLE_MATCH_THRESHOLD: "92"

      DATA_DIR: "/data"
      LISTEN_ADDR: ":8787"
      LOG_TIMEZONE: "Europe/Madrid"
      CACHE_REVALIDATE_HOURS: "24"

    volumes:
      - animeav1-mal-sync-data:/data

    security_opt:
      - seccomp=unconfined

volumes:
  animeav1-mal-sync-data:
    name: animeav1-mal-sync-data
